name: AchieveTracker
main: io.github.cats1337.Main
version: 0.0.3
api-version: 1.18
author: Cats

permissions:
  points.set:
    description: Set points
    default: op
  points.add:
    description: Add points
    default: op
  points.remove:
    description: Remove points
    default: op
  points.reset:
    description: Reset points
    default: op

commands:
    points:
      description: Show your points or someone else's points
      usage: /points
      aliases: [setpoints, addpoints, removepoints, resetpoints]

    setpoints:
      description: Set points
      usage: /points set <player> <points>
      permission: points.set
      permission-message : You don't have permission to this, stoopid
      # aliases: [set]

    addpoints:
      description: Add points
      usage: /points add <player> <points>
      permission: points.add
      permission-message : You don't have permission to this, stoopid
      # aliases: [add]

    removepoints:
      description: Remove points
      usage: /points remove <player> <points>
      permission: points.remove
      permission-message : You don't have permission to this, stoopid
      # aliases: [remove]

    resetpoints:
      description: Reset points
      usage: /points reset <player>
      permission: points.reset
      permission-message : You don't have permission to this, stoopid
      # aliases: [reset]
