name: AchieveTracker
main: io.github.cats1337.Main
version: 0.0.2
api-version: 1.15
author: Cats

permissions:
  points.view:
    description: View your points
    default: true


commands:
  points:
    # usage: /points [set|add|remove|reset] <player> [points]
    # default: op
    # permission:
    #   points.set
    #   points.add
    #   points.remove
    #   points.reset
    # permission-message: You don't have permission to this, stoopid


  # permissions:
  #   points.set:
  #     description: Set points
  #     default: op
  #   points.add:
  #     description: Add points
  #     default: op
  #   points.remove:
  #     description: Remove points
  #     default: op
  #   points.reset:
  #     description: Reset points
  #     default: op
    
  #   points:
  #   description: Show your points or someone else's points
  #   usage: /points

  #   points set:
  #   description: Set points
  #   usage: /points set <player> <points>
  #   permission: points.set
  #   permission-message : You don't have permission to this, stoopid

  #   points add:
  #   description: Add points
  #   usage: /points add <player> <points>
  #   permission: points.add
  #   permission-message : You don't have permission to this, stoopid

  #   points remove:
  #   description: Remove points
  #   usage: /points remove <player> <points>
  #   permission: points.remove
  #   permission-message : You don't have permission to this, stoopid

  #   points reset:
  #   description: Reset points
  #   usage: /points reset <player>
  #   permission: points.reset
  #   permission-message : You don't have permission to this, stoopid